//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public tbl_Category()
        {
            this.tbl_ContentLimitInsurance = new HashSet<tbl_ContentLimitInsurance>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }

		[System.Runtime.Serialization.IgnoreDataMember]
		public virtual ICollection<tbl_ContentLimitInsurance> tbl_ContentLimitInsurance { get; set; }
    }
}
